### ISSUE TITLE
Installation: data/atlas is not installed (thus not available)

### ISSUE THREAD

**Issue by SRSteinkamp** [alixlam/fmristroke#12]
It seems to that the data/atlas folder is not probably installed, downloaded when using pip install. 

This might be fixed here:
https://github.com/alixlam/fmristroke/blob/22b97a0ddd6f889a761751eb00f83b5505a0e99f/setup.py#L41C1-L41C81

Referencing the review here (https://github.com/openjournals/joss-reviews/issues/6636).

**Comment by alixlam** [comment]
Thank you very much @SRSteinkamp , it was indeed the source of the problem thank you for pointing it out. Should be installed now when installing the toolbox.
