### ISSUE TITLE
Minor suggested edits to the paper

### ISSUE THREAD

**Issue by SRSteinkamp** [alixlam/fmristroke#16]
Hi again, 

reviewing for JOSS (https://github.com/openjournals/joss-reviews/issues/6636) and I have a few very minor suggestions regarding the paper:

The last lines of the abstract (14 - 19), I feel, are a bit incomplete / confusing. I think very minor edits, would make them a lot more powerful. 

I'd further suggest to use "quality control" instead of "quality checks", throughout the paper - this might be only me, but "quality checks plots" does not feel right for me. 

Citation in line 41 is not correctly formatted.

In line 57, I think there is a "data" missing (as in "fMRI data").

**Comment by alixlam** [comment]
Thank you for your suggested edits. I changed the part in the abstract and hope it is a bit better. And corrected the little errors here and there. :)
